[package]
name = "uplink"
version = "1.2.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

[dependencies]
structopt = "0.3"
figment = { version = "0.10.6", features = ["toml", "json"] }
log = "0.4"
simplelog = "0.9"
disk = { path = "../disk" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-stream = "0.1"
tokio-compat-02 = "0.2.0"
flume = "0.10.9"
rumqttc = "0.7"
# rumqttc = { path = "../../rumqtt/rumqttc" }
bytes = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
anyhow = "1"
serde_json = "1.0"
rand = "0.7"
tunshell-client = { git = "https://github.com/TimeToogo/tunshell.git" }
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls"] }
futures-util = "0.3.14"
sysinfo = "0.21"
async-compression = { version = "0.3", features = ["tokio", "zstd"] }

[build-dependencies]
vergen = { version = "5.1", features = ["git", "build", "chrono"] }
