name: Releaser

on:
  release:
    types: [created]

jobs:
  create-release:
    name: Build release for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin, armv7-unknown-linux-muslabihf]
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/create-gh-release-action@v1
        with:
          target: ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  upload-release:
    name: Publish release for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin, armv7-unknown-linux-muslabihf]
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/upload-release-binary-action@v1
        with:
          bin: uplink
          archive: $bin-$tag-$target
          target: ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}